name = "brkt-starter-party"
main = "party/index.ts"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "BrktServer"
class_name = "BrktServer"

[[migrations]]
tag = "v1"
new_classes = ["BrktServer"]

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true